notifications:
  email:
    on_success: never
    on_failure: always

language: go

go:
- "1.10.x"
- "1.10"
- "1.9"

before_install:
  - go get -t -v ./...

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
